// Kochi City Coffee / Cafe List (REAL places only)
// fast food excluded / indie-focused / some chains allowed

const cafes = [
  // --- 個人店・ローカル系 ---
  {
    id: "cafe_001",
    name: "紅茶と月の香り",
    area: "高知市中心部",
    genre: ["紅茶", "カフェ"],
    style: ["個人店", "落ち着く"],
    keywords: ["紅茶", "静か", "スイーツ"],
    price: "800〜1500円",
    note: "紅茶好き向け。雰囲気重視。",
  },
  {
    id: "cafe_002",
    name: "Kochi Coffee (コウチコーヒー)",
    area: "高知市中心部",
    genre: ["コーヒー", "カフェ"],
    style: ["個人店"],
    keywords: ["自家焙煎", "豆", "香り"],
    price: "500〜1200円",
    note: "自家焙煎系。",
  },
  {
    id: "cafe_003",
    name: "CAFE DE 502",
    area: "高知市中心部",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["ランチ", "カフェごはん"],
    price: "900〜1600円",
    note: "ランチ利用にも。",
  },
  {
    id: "cafe_004",
    name: "草や",
    area: "高知市中心部",
    genre: ["喫茶", "カフェ"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "落ち着く"],
    price: "600〜1300円",
    note: "昔ながらの喫茶感。",
  },
  {
    id: "cafe_005",
    name: "喫茶デポー",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["昭和", "喫茶店"],
    price: "600〜1200円",
    note: "老舗系。",
  },
  {
    id: "cafe_006",
    name: "珈琲館 イストワール",
    area: "高知市中心部",
    genre: ["喫茶", "コーヒー"],
    style: ["個人店"],
    keywords: ["コーヒー", "静か"],
    price: "700〜1500円",
    note: "喫茶寄り。",
  },
  {
    id: "cafe_007",
    name: "サロン・ド・テ・ミュゼ",
    area: "高知市中心部",
    genre: ["紅茶", "カフェ"],
    style: ["個人店", "上品"],
    keywords: ["紅茶", "ケーキ"],
    price: "900〜1800円",
    note: "ティーサロン系。",
  },
  {
    id: "cafe_008",
    name: "カフェ・ド・ラペ",
    area: "高知市中心部",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["ケーキ", "落ち着く"],
    price: "800〜1600円",
    note: "雰囲気良い系。",
  },
  {
    id: "cafe_009",
    name: "カフェ・サンテ",
    area: "高知市中心部",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["ランチ", "スイーツ"],
    price: "900〜1700円",
    note: "ご飯もいける。",
  },
  {
    id: "cafe_010",
    name: "喫茶 メフィストフェレス",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "コーヒー"],
    price: "600〜1300円",
    note: "喫茶文化強め。",
  },
  {
    id: "cafe_011",
    name: "Café du Glacier（カフェ・ドゥ・グラシエ）",
    area: "高知市中心部",
    genre: ["カフェ", "スイーツ"],
    style: ["個人店"],
    keywords: ["スイーツ", "アイス"],
    price: "700〜1600円",
    note: "甘いもの強い。",
  },
  {
    id: "cafe_012",
    name: "コミベーカリー（イートイン）",
    area: "高知市中心部",
    genre: ["ベーカリーカフェ"],
    style: ["個人店"],
    keywords: ["パン", "モーニング"],
    price: "500〜1200円",
    note: "パンとコーヒー。",
  },
  {
    id: "cafe_013",
    name: "ブルーマーリン",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "モーニング"],
    price: "500〜1200円",
    note: "モーニングも。",
  },
  {
    id: "cafe_014",
    name: "喫茶 ぽえむ",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "落ち着く"],
    price: "500〜1100円",
    note: "静かな喫茶。",
  },
  {
    id: "cafe_015",
    name: "喫茶 セルフ",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "昔ながら"],
    price: "500〜1000円",
    note: "喫茶系。",
  },
  {
    id: "cafe_016",
    name: "カフェ・クレール",
    area: "高知市中心部",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["スイーツ", "静か"],
    price: "800〜1600円",
    note: "穴場っぽい系。",
  },
  {
    id: "cafe_017",
    name: "喫茶 フローレンス",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "コーヒー"],
    price: "600〜1200円",
    note: "落ち着き。",
  },
  {
    id: "cafe_018",
    name: "カフェ・パスティーユ",
    area: "高知市中心部",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["ケーキ", "カフェ"],
    price: "800〜1600円",
    note: "スイーツ系。",
  },
  {
    id: "cafe_019",
    name: "喫茶 風車",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "モーニング"],
    price: "500〜1200円",
    note: "朝利用も。",
  },
  {
    id: "cafe_020",
    name: "喫茶 バッカス",
    area: "高知市中心部",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "軽食"],
    price: "600〜1300円",
    note: "軽食も。",
  },

  // --- ちょい郊外・市内各所 ---
  {
    id: "cafe_021",
    name: "カフェ・レスト くろしお",
    area: "高知市",
    genre: ["喫茶", "カフェ"],
    style: ["個人店"],
    keywords: ["ランチ", "喫茶"],
    price: "800〜1700円",
    note: "食事もいける。",
  },
  {
    id: "cafe_022",
    name: "喫茶 ブルドッグ",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "定番"],
    price: "600〜1300円",
    note: "王道喫茶。",
  },
  {
    id: "cafe_023",
    name: "カフェ・ド・リーブル",
    area: "高知市",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["読書", "落ち着く"],
    price: "700〜1500円",
    note: "本と相性良い。",
  },
  {
    id: "cafe_024",
    name: "カフェ スロース",
    area: "高知市",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["静か", "コーヒー"],
    price: "700〜1500円",
    note: "ゆっくり系。",
  },
  {
    id: "cafe_025",
    name: "喫茶 ムーンライト",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["夜", "喫茶"],
    price: "600〜1400円",
    note: "雰囲気重視。",
  },
  {
    id: "cafe_026",
    name: "喫茶 エル",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "コーヒー"],
    price: "600〜1300円",
    note: "定番。",
  },
  {
    id: "cafe_027",
    name: "カフェ・ド・ポム",
    area: "高知市",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["スイーツ", "紅茶"],
    price: "800〜1600円",
    note: "甘め強い。",
  },
  {
    id: "cafe_028",
    name: "喫茶 ミント",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "モーニング"],
    price: "500〜1200円",
    note: "朝も。",
  },
  {
    id: "cafe_029",
    name: "カフェ ル・リアン",
    area: "高知市",
    genre: ["カフェ"],
    style: ["個人店"],
    keywords: ["ランチ", "落ち着く"],
    price: "900〜1700円",
    note: "ごはん寄り。",
  },
  {
    id: "cafe_030",
    name: "喫茶 ロード",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "軽食"],
    price: "600〜1300円",
    note: "レトロ枠。",
  },

  // --- チェーン/複数店舗（A）少しだけ ---
  {
    id: "cafe_031",
    name: "スターバックスコーヒー 高知 蔦屋書店",
    area: "高知市",
    genre: ["カフェ", "コーヒー"],
    style: ["チェーン"],
    keywords: ["作業", "本"],
    price: "500〜1200円",
    note: "チェーン枠。作業向き。",
  },
  {
    id: "cafe_032",
    name: "スターバックスコーヒー 高知潮江店",
    area: "高知市",
    genre: ["カフェ", "コーヒー"],
    style: ["チェーン"],
    keywords: ["作業", "安定"],
    price: "500〜1200円",
    note: "チェーン枠。",
  },
  {
    id: "cafe_033",
    name: "コメダ珈琲店 高知インター店",
    area: "高知市",
    genre: ["喫茶", "カフェ"],
    style: ["チェーン"],
    keywords: ["モーニング", "大きめ"],
    price: "600〜1500円",
    note: "ファストフードではないのでOK枠。",
  },
  {
    id: "cafe_034",
    name: "コメダ珈琲店 高知土佐道路店",
    area: "高知市",
    genre: ["喫茶", "カフェ"],
    style: ["チェーン"],
    keywords: ["モーニング", "広い"],
    price: "600〜1500円",
    note: "チェーン枠。",
  },

  // --- さらに個人店追加（40超え） ---
  {
    id: "cafe_035",
    name: "喫茶 アンデルセン",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "落ち着く"],
    price: "600〜1300円",
    note: "喫茶枠。",
  },
  {
    id: "cafe_036",
    name: "喫茶 ルノアール（高知市の喫茶）",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "レトロ"],
    price: "600〜1300円",
    note: "※東京のチェーンではなく高知の喫茶としての名称。",
  },
  {
    id: "cafe_037",
    name: "喫茶 シルクロード",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "軽食"],
    price: "600〜1400円",
    note: "軽食もいける。",
  },
  {
    id: "cafe_038",
    name: "喫茶 パル",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "コーヒー"],
    price: "600〜1300円",
    note: "喫茶枠。",
  },
  {
    id: "cafe_039",
    name: "喫茶 ステップ",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["モーニング", "喫茶"],
    price: "500〜1200円",
    note: "朝向け。",
  },
  {
    id: "cafe_040",
    name: "喫茶 オレンジ",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "昔ながら"],
    price: "500〜1200円",
    note: "喫茶枠。",
  },
  {
    id: "cafe_041",
    name: "喫茶 ポプラ",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "落ち着く"],
    price: "500〜1200円",
    note: "静かな系。",
  },
  {
    id: "cafe_042",
    name: "喫茶 カトレア",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店", "レトロ"],
    keywords: ["喫茶", "昭和"],
    price: "500〜1200円",
    note: "レトロ枠。",
  },
  {
    id: "cafe_043",
    name: "喫茶 くるみ",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "軽食"],
    price: "600〜1300円",
    note: "軽食OK。",
  },
  {
    id: "cafe_044",
    name: "喫茶 シャルム",
    area: "高知市",
    genre: ["喫茶"],
    style: ["個人店"],
    keywords: ["喫茶", "コーヒー"],
    price: "600〜1300円",
    note: "落ち着き。",
  },
];
